# Stage 1: Build the application
FROM node:20 AS build

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy application files
COPY . .

# Build the Next.js application
RUN npm run build

# Stage 2: Serve the application
FROM node:20-alpine AS production

# Set working directory
WORKDIR /app

# Install production dependencies
COPY package*.json ./
RUN npm install ci

# Copy built files from the build stage
COPY --from=build /app/.next .next
COPY --from=build /app/public public
COPY --from=build /app/node_modules node_modules
COPY --from=build /app/package.json .

# Expose port
EXPOSE 3001

# Start the application
CMD ["npm", "start"]